name: Clang Format Check
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  clang-format-and-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install Eigen3
        uses: kupns-aka-kupa/setup-eigen3@v1
        with:
          version: 3.4.0
      - name: Configure
        run: |
          sudo apt-get install -y ninja-build libgtest-dev libgmock-dev
          cmake --preset ci
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          # only 'update' a single comment in a pull request thread.
          database: "${{ github.workspace }}/build/ci"
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
      - name: Build
        run:
          cmake --build --preset build-ci
      - name: Run tests
        run: ctest --preset test-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov_include: src/.* include/.*
